# --- Main Colors ---
background            #131316
foreground            #e4e1e5
cursor                #e4e1e5
cursor_text_color     #131316

selection_background  #464857
selection_foreground  #e1e3f5

url_color             #dec48a

# --- ANSI Colors ---
color0                #131316
color1                #ffb4ab
color2                #dec48a
color3                #c4c5d7
color4                #bdc5ed
color5                #dec48a
color6                #c4c5d7
color7                #e4e1e5

color8                #45464e
color9                #93000a
color10               #645122
color11               #464857
color12               #4a5274
color13               #434654
color14               #564416
color15               #c6c5cf

# --- Starship Prompt Bubbles ---
color255              #4a5274
color254              #bdc5ed
color253              #464857
color252              #c4c5d7
color251              #645122
color250              #dec48a
color249              #93000a
color248              #ffb4ab

color232              #f6f5ff
color233              #272f4f
color234              #e1e3f5
color235              #2d303d
color236              #fff5e5
color237              #3e2e02
color238              #ffdad6
color239              #690005
color240              #f6f5ff
color241			  #353437

# Matched with unthemed light/dark
color243              #bdc5ed
color244              #ffb4ab
color245              #45464e

# --- UI Elements ---
active_tab_foreground   #272f4f
active_tab_background   #bdc5ed
inactive_tab_foreground #f6f5ff
inactive_tab_background #4a5274

active_border_color     #bdc5ed
inactive_border_color   #909098

# --- Marks ---
mark1_foreground        #111a38
mark1_background        #dce1ff
mark2_foreground        #181b28
mark2_background        #e0e1f3
mark3_foreground        #251a00
mark3_background        #fbe0a3
