cursor #e3e3d9
cursor_text_color #c4c8b7

foreground            #e3e3d9
background            #12140e
selection_foreground  #293417
selection_background  #bdcca2
url_color             #b0d27b

# black
color8   #262626
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #b0d27b
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #b0d27b

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0

color19 #223600
