# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e3e3d9"

# Title color for boxes
theme[title]="#b0d27b"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bdcca2"

# Background color of selected item in processes box
theme[selected_bg]="#b0d27b"

# Foreground color of selected item in processes box
theme[selected_fg]="#223600"

# Color of inactive/disabled text
theme[inactive_fg]="#c4c8b7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#faaeec"

# Cpu box outline color
theme[cpu_box]="#8e9383"

# Memory/disks box outline color
theme[mem_box]="#8e9383"

# Net up/down box outline color
theme[net_box]="#8e9383"

# Processes box outline color
theme[proc_box]="#8e9383"

# Box divider line and small boxes line color
theme[div_line]="#44483b"

# Temperature graph colors
theme[temp_start]="#bdcca2"
theme[temp_mid]="#b0d27b"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bdcca2"
theme[cpu_mid]="#b0d27b"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bdcca2"
theme[free_mid]=""
theme[free_end]="#414d2d"

# Mem/Disk cached meter
theme[cached_start]="#faaeec"
theme[cached_mid]=""
theme[cached_end]="#bf7ab3"

# Mem/Disk available meter
theme[available_start]="#b0d27b"
theme[available_mid]=""
theme[available_end]="#7b9b4a"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bdcca2"
theme[download_mid]="#b0d27b"
theme[download_end]="#faaeec"

# Upload graph colors
theme[upload_start]="#bdcca2"
theme[upload_mid]="#b0d27b"
theme[upload_end]="#faaeec"
